import type { Meta, StoryObj } from '@storybook/html';
import { mountTool } from '../../../stories/_helpers/mount-tool';
import { tool } from './index';
import { DEFAULT_STATE, type State } from './url-state';

// Generated by `pnpm new-tool` — replace TODOs with tool-specific state.
//
// Convention: every tool story exports `Default`, `Empty`, `Error`, and
// `WithMaxInput`. Coverage gate (#48 / SB-10) enforces this contract.

const meta: Meta<State> = {
  title: 'Tools / __CATEGORY__ / __NAME__',
  parameters: {
    docs: {
      description: {
        component:
          // Spec link convention (#68 / SB-CC-3) — kept relative so the
          // link works regardless of where Storybook is deployed.
          'See spec: [.specification/__SLUG__.md](./../../../.specification/__SLUG__.md)',
      },
    },
  },
};

export default meta;

export const Default: StoryObj<State> = {
  render: (): HTMLElement => mountTool(tool, DEFAULT_STATE),
};

export const Empty: StoryObj<State> = {
  // TODO: adjust if `DEFAULT_STATE` is not the empty state for this tool.
  render: (): HTMLElement => mountTool(tool, DEFAULT_STATE),
};

export const Error: StoryObj<State> = {
  // TODO: replace with an invalid-input state that surfaces an error UI.
  render: (): HTMLElement => mountTool(tool, DEFAULT_STATE),
};

export const WithMaxInput: StoryObj<State> = {
  // TODO: replace with a stress-test state near the practical input cap.
  render: (): HTMLElement => mountTool(tool, DEFAULT_STATE),
};
