/**
 * Lazy tool manifest — the sidebar/home grid pulls metadata synchronously
 * from this file, but the actual `render` / `parseParams` / `serializeParams`
 * implementations are only loaded when the user routes into the tool.
 *
 * Each `load()` call is a dynamic `import()` so Vite emits one chunk per
 * tool. As we approach 100 tools, this prevents shipping every crypto
 * library, BIP39 wordlist, smol-toml, js-yaml, etc. on first paint.
 *
 * The auto-generated portions are guarded by the comment markers below;
 * `pnpm new-tool` updates them in place.
 */

import type { ToolManifest, ToolModule } from '../lib/types';

// Tiny helper — adapts the named-export shape (`{ tool }`) to the
// promise we expose via `ToolManifest.load()`.
const lazy = <S>(p: Promise<{ tool: ToolModule<S> }>): Promise<ToolModule<unknown>> =>
  p.then((m) => m.tool as unknown as ToolModule<unknown>);

export const MANIFEST: readonly ToolManifest[] = [
  {
    id: 'base64-string-converter',
    number: 1,
    category: '01-encoding',
    name: 'Base64 string converter',
    description:
      'Encode/decode UTF-8 strings to and from base64 (with optional URL-safe variant).',
    tags: ['base64', 'encoding', 'string'],
    load: () => lazy(import('./01-encoding/001-base64-string-converter')),
  },
  {
    id: 'base64-basic-auth',
    number: 2,
    category: '01-encoding',
    name: 'Basic Auth helper',
    description:
      'Build or decode HTTP Basic Auth credentials — base64(`user:pass`) and back.',
    tags: ['basic-auth', 'http', 'base64'],
    load: () => lazy(import('./01-encoding/002-base64-basic-auth')),
  },
  {
    id: 'html-entities',
    number: 3,
    category: '01-encoding',
    name: 'HTML entities',
    description: 'Encode and decode HTML entities — named, numeric, or hex.',
    tags: ['html', 'entities', 'encode'],
    load: () => lazy(import('./01-encoding/003-html-entities')),
  },
  {
    id: 'url-encode-decode',
    number: 4,
    category: '01-encoding',
    name: 'URL encode / decode',
    description: 'Percent-encode and decode URLs and components.',
    tags: ['url', 'percent-encoding'],
    load: () => lazy(import('./01-encoding/004-url-encode-decode')),
  },
  {
    id: 'jwt-decoder',
    number: 5,
    category: '01-encoding',
    name: 'JWT decoder',
    description:
      'Decode JSON Web Tokens — header, payload, signature. Optional HMAC verification.',
    tags: ['jwt', 'jose', 'decoder'],
    load: () => lazy(import('./01-encoding/005-jwt-decoder')),
  },
  {
    id: 'uuid',
    number: 6,
    category: '10-data',
    name: 'UUID generator',
    description: 'Generate v4 UUIDs with anatomy breakdown per RFC 4122 §4.1.',
    tags: ['uuid', 'guid', 'random'],
    load: () => lazy(import('./10-data/006-uuid')),
  },
  {
    id: 'ulid',
    number: 7,
    category: '10-data',
    name: 'ULID generator',
    description: 'Lexicographically sortable, time-prefixed identifiers.',
    tags: ['ulid', 'sortable', 'identifier'],
    load: () => lazy(import('./10-data/007-ulid')),
  },
  {
    id: 'password',
    number: 8,
    category: '10-data',
    name: 'Password generator',
    description: 'Strong, random passwords with entropy + crack-time meter.',
    tags: ['password', 'random', 'entropy'],
    load: () => lazy(import('./10-data/008-password')),
  },
  {
    id: 'hash',
    number: 9,
    category: '02-crypto',
    name: 'Hash text',
    description: 'SHA-1 / 256 / 384 / 512 of any UTF-8 string — all four shown at once.',
    tags: ['hash', 'sha', 'crypto'],
    load: () => lazy(import('./02-crypto/009-hash')),
  },
  {
    id: 'case',
    number: 10,
    category: '03-converter',
    name: 'Case converter',
    description: 'camelCase, snake_case, kebab-case, PascalCase, SCREAMING_SNAKE.',
    tags: ['case', 'string'],
    load: () => lazy(import('./03-converter/010-case')),
  },
  {
    id: 'base-converter',
    number: 11,
    category: '07-math',
    name: 'Base converter',
    description: 'Convert numbers between bases 2, 8, 10, 16 (and arbitrary 2-36).',
    tags: ['base', 'radix', 'number'],
    load: () => lazy(import('./07-math/011-base-converter')),
  },
  {
    id: 'roman',
    number: 12,
    category: '07-math',
    name: 'Roman numerals',
    description: 'Convert between Arabic and Roman numerals.',
    tags: ['roman', 'numerals', 'number'],
    load: () => lazy(import('./07-math/012-roman')),
  },
  {
    id: 'nato',
    number: 13,
    category: '09-text',
    name: 'NATO phonetic',
    description: 'Spell out a string using the NATO phonetic alphabet.',
    tags: ['nato', 'phonetic', 'spelling'],
    load: () => lazy(import('./09-text/013-nato')),
  },
  {
    id: 'wordcount',
    number: 14,
    category: '09-text',
    name: 'Word count',
    description: 'Count words, characters, paragraphs, reading time.',
    tags: ['wordcount', 'text', 'stats'],
    load: () => lazy(import('./09-text/014-wordcount')),
  },
  {
    id: 'lorem',
    number: 15,
    category: '09-text',
    name: 'Lorem ipsum',
    description: 'Generate placeholder paragraphs.',
    tags: ['lorem', 'placeholder'],
    load: () => lazy(import('./09-text/015-lorem')),
  },
  {
    id: 'chmod',
    number: 16,
    category: '08-measurement',
    name: 'Chmod calculator',
    description: 'Translate between symbolic and octal Unix file permissions.',
    tags: ['chmod', 'unix', 'permissions'],
    load: () => lazy(import('./08-measurement/016-chmod')),
  },
  {
    id: 'ascii-binary',
    number: 17,
    category: '01-encoding',
    name: 'ASCII / binary',
    description: 'Convert text to and from binary, octal, decimal, hex.',
    tags: ['ascii', 'binary', 'hex'],
    load: () => lazy(import('./01-encoding/017-ascii-binary')),
  },
  {
    id: 'color',
    number: 18,
    category: '03-converter',
    name: 'Color converter',
    description: 'HEX ⇄ RGB ⇄ HSL ⇄ OKLCH with a live swatch.',
    tags: ['color', 'oklch', 'hsl'],
    load: () => lazy(import('./03-converter/018-color')),
  },
  {
    id: 'text-unicode',
    number: 19,
    category: '09-text',
    name: 'Unicode inspector',
    description: 'Inspect Unicode code points, names, blocks.',
    tags: ['unicode', 'codepoint'],
    load: () => lazy(import('./09-text/019-text-unicode')),
  },
  {
    id: 'format-json',
    number: 20,
    category: '06-development',
    name: 'JSON formatter',
    description: 'Pretty-print, minify, and validate JSON.',
    tags: ['json', 'format'],
    load: () => lazy(import('./06-development/020-format-json')),
  },
  {
    id: 'regex',
    number: 21,
    category: '06-development',
    name: 'Regex tester',
    description: 'Test JavaScript regex with match highlighting and named captures.',
    tags: ['regex', 'pattern'],
    load: () => lazy(import('./06-development/021-regex')),
  },
  {
    id: 'diff',
    number: 22,
    category: '06-development',
    name: 'Diff',
    description: 'Line and word-level diff with stats.',
    tags: ['diff', 'compare'],
    load: () => lazy(import('./06-development/022-diff')),
  },
  {
    id: 'math-eval',
    number: 23,
    category: '07-math',
    name: 'Math evaluator',
    description: 'Evaluate arithmetic expressions with sane operator precedence.',
    tags: ['math', 'calculator'],
    load: () => lazy(import('./07-math/023-math-eval')),
  },
  {
    id: 'datetime',
    number: 24,
    category: '04-web',
    name: 'Datetime converter',
    description: 'Convert between Unix timestamps, ISO 8601, and human-friendly formats.',
    tags: ['datetime', 'unix', 'iso8601'],
    load: () => lazy(import('./04-web/024-datetime')),
  },
  {
    id: 'user-agent',
    number: 25,
    category: '04-web',
    name: 'User agent parser',
    description: 'Decode a User-Agent string into browser, OS, device.',
    tags: ['user-agent', 'browser'],
    load: () => lazy(import('./04-web/025-user-agent')),
  },
  {
    id: 'token-generator',
    number: 26,
    category: '02-crypto',
    name: 'Token generator',
    description: 'Random alphanumeric / hex / base64 tokens with entropy.',
    tags: ['token', 'random', 'crypto'],
    load: () => lazy(import('./02-crypto/026-token-generator')),
  },
  {
    id: 'hmac',
    number: 27,
    category: '02-crypto',
    name: 'HMAC',
    description: 'HMAC-SHA-1/256/384/512 with hex output.',
    tags: ['hmac', 'sha', 'crypto'],
    load: () => lazy(import('./02-crypto/027-hmac')),
  },
  {
    id: 'base64-file',
    number: 28,
    category: '01-encoding',
    name: 'Base64 file',
    description: 'Encode files to base64 / data URIs and decode back to a download.',
    tags: ['base64', 'file', 'data-uri'],
    load: () => lazy(import('./01-encoding/028-base64-file')),
  },
  {
    id: 'rsa-keypair',
    number: 29,
    category: '02-crypto',
    name: 'RSA key pair',
    description: 'Generate RSASSA-PKCS1-v1_5 key pairs (2048/3072/4096) as PEM.',
    tags: ['rsa', 'keypair', 'pem'],
    load: () => lazy(import('./02-crypto/029-rsa-keypair')),
  },
  {
    id: 'encrypt',
    number: 30,
    category: '02-crypto',
    name: 'AES-GCM encrypt',
    description: 'AES-256-GCM with PBKDF2-derived keys (250k iterations).',
    tags: ['encryption', 'aes', 'pbkdf2'],
    load: () => lazy(import('./02-crypto/030-encrypt')),
  },
  {
    id: 'yaml-json',
    number: 31,
    category: '03-converter',
    name: 'YAML → JSON',
    description: 'Convert YAML to JSON.',
    tags: ['yaml', 'json'],
    load: () => lazy(import('./03-converter/031-yaml-json')),
  },
  {
    id: 'yaml-toml',
    number: 32,
    category: '03-converter',
    name: 'YAML → TOML',
    description: 'Convert YAML to TOML.',
    tags: ['yaml', 'toml'],
    load: () => lazy(import('./03-converter/032-yaml-toml')),
  },
  {
    id: 'json-yaml',
    number: 33,
    category: '03-converter',
    name: 'JSON → YAML',
    description: 'Convert JSON to YAML.',
    tags: ['json', 'yaml'],
    load: () => lazy(import('./03-converter/033-json-yaml')),
  },
  {
    id: 'json-toml',
    number: 34,
    category: '03-converter',
    name: 'JSON → TOML',
    description: 'Convert JSON to TOML.',
    tags: ['json', 'toml'],
    load: () => lazy(import('./03-converter/034-json-toml')),
  },
  {
    id: 'bip39',
    number: 35,
    category: '02-crypto',
    name: 'BIP39 mnemonic',
    description:
      'Generate a BIP39 seed phrase (12/15/18/21/24 words, English wordlist). Decodes back to entropy.',
    tags: ['bip39', 'mnemonic', 'seed-phrase'],
    load: () => lazy(import('./02-crypto/035-bip39')),
  },
  {
    id: 'bcrypt',
    number: 36,
    category: '02-crypto',
    name: 'Bcrypt hash',
    description:
      'Hash a password with bcrypt (cost 4–14, automatic salt) or verify against an existing $2a/$2b hash.',
    tags: ['bcrypt', 'password', 'hash'],
    load: () => lazy(import('./02-crypto/036-bcrypt')),
  },
];
